### ISSUE TITLE
GPL-compatible?

### ISSUE THREAD

**Issue by MrCustomizer** [OlivierLD/raspberry-coffee#8]
Can I use your code in an Open Source Project under the [GPLv3 license](https://www.gnu.org/licenses/gpl-3.0.en.html)? I couldn't find any licensing information in your repository.

**Comment by OlivierLD** [comment]
Yes, please use it! Thanks for asking.

**Comment by MrCustomizer** [comment]
Thanks a lot. For reference, this is the project I'm working on (it's currently in a pretty early phase as I'm trying to port my beta version from C++ to Kotlin): https://github.com/MrCustomizer/TimeyWimey

**Comment by msurguy** [comment]
@OlivierLD Hello! I am thankful for this library and your recent activity putting so much work into it.

I am currently in talks with Gottfried Haider about contributing a lot to the capabilities of using Processing on the Raspberry Pi. I don't have much experience with Java so far but am willing to learn the development process and the language. This repository gives me a lot of inspiration and can be a bridge between what we have now and what we'd like to end up with (Processing on the Pi more accessible to others).

I was wondering if you have some suggestions of how I could use the I2C sensors without using the Pi4J library in Processing. For example, would it be possible to use ADC or Accelerometer sensor just by using Processing's built in I2C library? An example I saw previously for controlling SSD1306 was this one : https://github.com/gohai/computationalculture-workshop/tree/master/TemplateLCD.

My priority is to make a couple sensors work with Processing without being dependent on pi4j: ADS1115 and CAP1188. 

Any suggestions would be welcome and would be appreciated!
Thanks!

**Comment by OlivierLD** [comment]
HI @msurguy !
That sounds interesting... Based on Gottfried Haider's work, I've also interfaced an SSD1306 (See at https://github.com/OlivierLD/JavaHard). 
Adding an ADS1115 should not be a problem, this would be an opportunity to move the project forward!
And using Processing on top of that is straight forward (https://github.com/OlivierLD/raspberry-pi4j-samples/tree/master/Processing). What I would love is Processing to support Java 8...

I'll see what I can do, will give you a ping when there is something for you to play with.

**Comment by msurguy** [comment]
@OlivierLD thanks for looking into this! I'd be interested in knowing the process of converting a Python library or C library to be Java - Processing compatible. Any tips on that would help me greatly!

**Comment by OlivierLD** [comment]
@msurguy, please see [here](https://github.com/OlivierLD/JavaHard/issues/4).
